--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

-- Started on 2020-09-18 14:46:58

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 26094)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 204 (class 1259 OID 26101)
-- Name: cat_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cat_categoria (
    id_categoria bigint NOT NULL,
    ds_descripcion text,
    "b_Activo" boolean NOT NULL
);


ALTER TABLE public.cat_categoria OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 26099)
-- Name: cat_categoria_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cat_categoria ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_categoria_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 206 (class 1259 OID 26111)
-- Name: cat_marca; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cat_marca (
    id_marca bigint NOT NULL,
    ds_descripcion text,
    b_activo boolean NOT NULL
);


ALTER TABLE public.cat_marca OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 26109)
-- Name: cat_marca_id_marca_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cat_marca ALTER COLUMN id_marca ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_marca_id_marca_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 26121)
-- Name: cat_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cat_proveedor (
    id_proveedor bigint NOT NULL,
    ds_descripcion text,
    b_activo boolean NOT NULL
);


ALTER TABLE public.cat_proveedor OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 26119)
-- Name: cat_proveedor_id_proveedor_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cat_proveedor ALTER COLUMN id_proveedor ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_proveedor_id_proveedor_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 26131)
-- Name: cat_unidad_medida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cat_unidad_medida (
    id_unidad_medida bigint NOT NULL,
    ds_descripcion text,
    b_activo boolean NOT NULL
);


ALTER TABLE public.cat_unidad_medida OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 26129)
-- Name: cat_unidad_medida_id_unidad_medida_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cat_unidad_medida ALTER COLUMN id_unidad_medida ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cat_unidad_medida_id_unidad_medida_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 26141)
-- Name: tb_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_producto (
    id_producto bigint NOT NULL,
    ds_sku text,
    ds_descripcion text,
    f_precio_venta numeric NOT NULL,
    f_costo numeric NOT NULL,
    ds_imagen text,
    id_proveedor bigint NOT NULL,
    id_categoria bigint NOT NULL,
    id_marca bigint NOT NULL,
    id_unidad_medida bigint NOT NULL,
    b_activo boolean NOT NULL
);


ALTER TABLE public.tb_producto OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 26139)
-- Name: tb_producto_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_producto ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_producto_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2866 (class 0 OID 26094)
-- Dependencies: 202
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20200917232029_qaz	3.1.8
\.


--
-- TOC entry 2868 (class 0 OID 26101)
-- Dependencies: 204
-- Data for Name: cat_categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cat_categoria (id_categoria, ds_descripcion, "b_Activo") FROM stdin;
1	Casa	t
2	Oficina	t
3	Salud	t
\.


--
-- TOC entry 2870 (class 0 OID 26111)
-- Dependencies: 206
-- Data for Name: cat_marca; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cat_marca (id_marca, ds_descripcion, b_activo) FROM stdin;
1	Marca 1	t
3	Marca Editada	t
2	Marca 2	f
4	Marca 5	t
5	Marca 5	t
6	Marca 7	t
\.


--
-- TOC entry 2872 (class 0 OID 26121)
-- Dependencies: 208
-- Data for Name: cat_proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cat_proveedor (id_proveedor, ds_descripcion, b_activo) FROM stdin;
1	Proveedor 1	t
2	Proveedor 2	t
3	Proveedor 3	t
4	Proveedor 4	t
5	Proveedor 5 editadoooo x	t
6	Proveedor 6	t
7	Proveedor 6	t
\.


--
-- TOC entry 2874 (class 0 OID 26131)
-- Dependencies: 210
-- Data for Name: cat_unidad_medida; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cat_unidad_medida (id_unidad_medida, ds_descripcion, b_activo) FROM stdin;
1	Caja	t
2	Pieza	t
3	Metro 2	t
4	Metro	t
\.


--
-- TOC entry 2876 (class 0 OID 26141)
-- Dependencies: 212
-- Data for Name: tb_producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_producto (id_producto, ds_sku, ds_descripcion, f_precio_venta, f_costo, ds_imagen, id_proveedor, id_categoria, id_marca, id_unidad_medida, b_activo) FROM stdin;
2	SKU26112016 E	Producto 1E	100	85	NA	1	1	2	2	t
3	SKU26112016	Producto 12	100.55	85.35		1	1	1	1	t
\.


--
-- TOC entry 2882 (class 0 OID 0)
-- Dependencies: 203
-- Name: cat_categoria_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cat_categoria_id_categoria_seq', 3, true);


--
-- TOC entry 2883 (class 0 OID 0)
-- Dependencies: 205
-- Name: cat_marca_id_marca_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cat_marca_id_marca_seq', 6, true);


--
-- TOC entry 2884 (class 0 OID 0)
-- Dependencies: 207
-- Name: cat_proveedor_id_proveedor_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cat_proveedor_id_proveedor_seq', 7, true);


--
-- TOC entry 2885 (class 0 OID 0)
-- Dependencies: 209
-- Name: cat_unidad_medida_id_unidad_medida_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cat_unidad_medida_id_unidad_medida_seq', 4, true);


--
-- TOC entry 2886 (class 0 OID 0)
-- Dependencies: 211
-- Name: tb_producto_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_producto_id_producto_seq', 3, true);


--
-- TOC entry 2721 (class 2606 OID 26098)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 2723 (class 2606 OID 26108)
-- Name: cat_categoria PK_cat_categoria; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cat_categoria
    ADD CONSTRAINT "PK_cat_categoria" PRIMARY KEY (id_categoria);


--
-- TOC entry 2725 (class 2606 OID 26118)
-- Name: cat_marca PK_cat_marca; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cat_marca
    ADD CONSTRAINT "PK_cat_marca" PRIMARY KEY (id_marca);


--
-- TOC entry 2727 (class 2606 OID 26128)
-- Name: cat_proveedor PK_cat_proveedor; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cat_proveedor
    ADD CONSTRAINT "PK_cat_proveedor" PRIMARY KEY (id_proveedor);


--
-- TOC entry 2729 (class 2606 OID 26138)
-- Name: cat_unidad_medida PK_cat_unidad_medida; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cat_unidad_medida
    ADD CONSTRAINT "PK_cat_unidad_medida" PRIMARY KEY (id_unidad_medida);


--
-- TOC entry 2735 (class 2606 OID 26148)
-- Name: tb_producto PK_tb_producto; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_producto
    ADD CONSTRAINT "PK_tb_producto" PRIMARY KEY (id_producto);


--
-- TOC entry 2730 (class 1259 OID 26169)
-- Name: IX_tb_producto_id_categoria; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_tb_producto_id_categoria" ON public.tb_producto USING btree (id_categoria);


--
-- TOC entry 2731 (class 1259 OID 26170)
-- Name: IX_tb_producto_id_marca; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_tb_producto_id_marca" ON public.tb_producto USING btree (id_marca);


--
-- TOC entry 2732 (class 1259 OID 26171)
-- Name: IX_tb_producto_id_proveedor; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_tb_producto_id_proveedor" ON public.tb_producto USING btree (id_proveedor);


--
-- TOC entry 2733 (class 1259 OID 26172)
-- Name: IX_tb_producto_id_unidad_medida; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_tb_producto_id_unidad_medida" ON public.tb_producto USING btree (id_unidad_medida);


--
-- TOC entry 2736 (class 2606 OID 26149)
-- Name: tb_producto fk_cat_categoria_id_categoria; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_producto
    ADD CONSTRAINT fk_cat_categoria_id_categoria FOREIGN KEY (id_categoria) REFERENCES public.cat_categoria(id_categoria) ON DELETE CASCADE;


--
-- TOC entry 2737 (class 2606 OID 26154)
-- Name: tb_producto fk_cat_marca_id_marca; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_producto
    ADD CONSTRAINT fk_cat_marca_id_marca FOREIGN KEY (id_marca) REFERENCES public.cat_marca(id_marca) ON DELETE CASCADE;


--
-- TOC entry 2738 (class 2606 OID 26159)
-- Name: tb_producto fk_cat_proveedor_id_proveedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_producto
    ADD CONSTRAINT fk_cat_proveedor_id_proveedor FOREIGN KEY (id_proveedor) REFERENCES public.cat_proveedor(id_proveedor) ON DELETE CASCADE;


--
-- TOC entry 2739 (class 2606 OID 26164)
-- Name: tb_producto fk_cat_unidad_medida_id_unidad_medida; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_producto
    ADD CONSTRAINT fk_cat_unidad_medida_id_unidad_medida FOREIGN KEY (id_unidad_medida) REFERENCES public.cat_unidad_medida(id_unidad_medida) ON DELETE CASCADE;


-- Completed on 2020-09-18 14:47:00

--
-- PostgreSQL database dump complete
--

